alphabet = [chr(i) for i in range(65, 91)]

def original(message, shift):
    original_message2=""
    for i in message:
        new_encr_i=(alphabet.index(i)-shift)%26
        original_message2+=str(alphabet[new_encr_i])
    return original_message2

input_file="ITWDMBPIBQKIVBMFXTIQVINMMTQVOQKIVJIZMTGKWVBIQVUGPMIZBAWNCTTWNMUWBQWVUGNMMTQVOAAWWNBMVQVUWBQWVQBATQSMIAEMMBACUUMZAJZMMHMEMIDQVOBPZWCOPBPMBZMMAJZQVOQVOEQBPQBIOMVBTMKITUINMMTQVOBPIBKIVLWPIZUBPMEIGQBNQTTAUMEQBPRWGIAQNQUIVMENWCVLBWGUGPMIZBAWNCTTWNJTQAAQUIBIKWUXTMBMTWAANWZEWZLABPMXMZNMKBTWDMNWZUMQABPMWVMBPIBAMBAUMNZMMEPMZMQKIVJMUGAMTNIVLSVWEBPIBQUTWDMLNWZUM"
shift_value = 8
print(original(input_file,shift_value).count("LOVE"))

